services:
  - type: web
    name: trenera-volleyball
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_v3:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false

databases:
  - name: trenera-db
    databaseName: trenera
    user: trenera_user
    plan: free
